public enum EchoET
{
	SCROLL_ECHOUV = 0,
	SCROLL_SECTION_ECHOUV = 1,
	CELLANIM_ECHOUV = 2,
	CELLANIM_UVSET = 3,
	CELLANIM_BLEND = 4,
	RANDOM_ECHOUV = 5,
	ANIMATE_TILING = 6,
	SHIELD_ON = 7,
	SHIELD_OFF = 8,
	SHIELD_DOWN = 9,
	SHIELD_HIT = 10,
	FUSION = 11,
	ECHORGBA = 12,
	ECHOALPHA = 13,
	ECHOSCALE = 14,
	DISSOLVE = 15,
	RANDOM_MIX = 16,
	BLINK_ECHOUV = 17,
	BLINK_UVSET = 18,
	SHAKE_OBJECT = 19,
	CUSTOM = 20
}
